version: "3"
services:
  mysql:
    image: mysql
    container_name: projecte_mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - main
  app:
    build: ./frontend/
    ports:
      - ${CLIENT_PORT}:8080
    container_name: frontend
    networks:
      - main
  server:
    build: ./backend/
    ports:
      - ${SERVER_PORT}:8000
    container_name: backend
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
      - MYSQL_PORT
      - DJANGO_SECRET_KEY
    networks:
      - main
    depends_on:
      - mysql
networks:
  main:
    driver: bridge
    external: true

