version: "3"
services:
  db:
    image: mysql
    container_name: projecte_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "${MYSQL_PORT}:3306"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - main
    restart: always
  server:
    image: python:3.8.10
    command: sh -c "cd /backend/django_server; pip3 install -r requirements.txt; chmod +x waitforit.sh; ./waitforit.sh db:3306; python3 manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - ./backend/django_server:/backend/django_server
    container_name: backend
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
      - MYSQL_PORT
      - DJANGO_SECRET_KEY
    networks:
      - main
    depends_on:
      - db
    restart: always
  app:
    image: node:14.18.3
    ports:
      - ${CLIENT_PORT}:8080
    volumes:
      - ./frontend:/frontend
    container_name: frontend
    command: bash -c "cd /frontend; npm install && npm start"
    networks:
      - main
    depends_on:
      - server
    restart: always
networks:
  main:
    driver: bridge
    external: true
