version: "3"
services:
  db:
    image: mysql
    container_name: projecte_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - main
  server:
    build: ./backend/
    command: sh -c "chmod +x waitforit.sh; ./waitforit.sh db:3306; python3 manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    ports:
      - ${SERVER_PORT}:8000
    container_name: backend
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
      - MYSQL_PORT
      - DJANGO_SECRET_KEY
    networks:
      - main
    depends_on:
      - db
  app:
    build: ./frontend/
    ports:
      - ${CLIENT_PORT}:8080
    container_name: frontend
    command: bash -c "npm install && npm start"
    networks:
      - main
    depends_on:
      - server
networks:
  main:
    driver: bridge
    external: true

