# Generated by Django 3.0.2 on 2022-02-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user_followed', 'user_follow')},
        ),
    ]
